# Base
FROM docker.io/oven/bun:1.3 AS base
WORKDIR /app
COPY package*.json bun.lock ./

# Development
FROM base AS development
RUN bun install
COPY . .
CMD ["bun", "dev", "--host"]

# Build (Intermediate)
FROM base AS build-step
ARG VITE_BACKEND_URL=http://localhost:3000
ENV VITE_BACKEND_URL=$VITE_BACKEND_URL
RUN bun install --frozen-lockfile
COPY . .
RUN bun run build

# STAGE 4: Production
FROM base AS production
ENV NODE_ENV=production
COPY --from=build-step /app/node_modules ./node_modules
COPY --from=build-step /app/dist ./dist
CMD ["vite", "preview", "--host", "0.0.0.0", "--port", "4173"]
