services:
  datalake:
    image: docker.io/dxflrs/garage:v2.3.0
    restart: unless-stopped
    ports:
      - ${DATALAKE_CONN_HOST_PORT:-3900}:3900
      - ${DATALAKE_ADMIN_HOST_PORT:-3903}:3903
    environment:
      GARAGE_RPC_SECRET: "${GARAGE_RPC_SECRET-garagerpcsecretgaragerpcsecretgaragerpcsecretgaragerpcsecretgara}"
      GARAGE_ADMIN_SECRET: "${GARAGE_ADMIN_SECRET-superadminsecret}"
      GARAGE_ADMIN_TOKEN: "${GARAGE_ADMIN_SECRET-superadminsecret}"
      GARAGE_DEFAULT_BUCKET: "${GARAGE_BUCKET-default}"
      GARAGE_DEFAULT_ACCESS_KEY: "GK${GARAGE_DEFAULT_ACCESS_KEY-garagedefaultaccesskeygaragedefa}"
      GARAGE_DEFAULT_SECRET_KEY: "${GARAGE_DEFAULT_SECRET_KEY-garagedefaultsecretkeygaragedefaultsecretkeygaragedefaultsecretk}"
    env_file: .env
    volumes:
      - ./datalake/etc/garage.toml:/etc/garage.toml:ro
    command: /garage server --single-node --default-bucket

  backend:
    build:
      context: ./backend
      target: production
      dockerfile: Containerfile
    restart: unless-stopped
    develop:
      watch:
        - action: rebuild
          path: /app/package.json
    ports:
      - ${BACKEND_HOST_PORT:-3000}:3000
    volumes:
      - ./backend:/app:z
      - /app/node_modules
    env_file: .env
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./frontend
      target: production
      dockerfile: Containerfile
    restart: unless-stopped
    develop:
      watch:
        - action: rebuild
          path: /app/package.json
    ports:
      - ${FRONTEND_HOST_PORT:-5173}:5173
    volumes:
      - ./frontend:/app:z
      - /app/node_modules
    env_file: .env
    environment:
      - NODE_ENV=development

volumes:
  bun_cache:
  node_modules:
