# Base
FROM docker.io/oven/bun:1.3 AS base
WORKDIR /app
COPY package*.json bun.lock ./

# Development
FROM base AS development
RUN bun install
COPY . .
CMD ["bun", "dev", "--host"]

# Build (Intermediate)
FROM base AS build-step
RUN bun install --frozen-lockfile
COPY . .
RUN bun build \
  --compile \
  --minify-whitespace \
  --minify-syntax \
  --outfile server \
  src/index.ts

# STAGE 4: Production
FROM gcr.io/distroless/base as production
ENV NODE_ENV=production
COPY --from=build-step /app/server server
CMD ["./server"]
EXPOSE 3000
